pipeline.inputJson=src/main/resources/testdata/fictive-esrs-input.json
pipeline.mappingFile=mapping/map-esrs-2023-12-22.json
pipeline.templateFile=templates/report-base.xhtml
pipeline.layoutMap=mapping/report-layout-map.json
pipeline.outputDir=output
pipeline.taxonomyRoot=.

pipeline.arelle.command=arelleCmdLine
pipeline.arelle.skip=true
pipeline.validation.failOnIssues=true
pipeline.viewer.requirePlugin=false
pipeline.arelle.disclosureSystem=
pipeline.arelle.logFormat=
pipeline.viewer.plugin=iXBRLViewerPlugin
